version: "3.5"
services:
  appweb:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "8098665663"
      ACCEPT_EULA: "Y"